apiVersion: v1
kind: Service
metadata:
  name: itunes-scraper-analyzer
  labels:
    app: itunes-scraper
spec:
  ports:
    - port: 3000
  selector:
    controller-uid: itunes-scraper-analyzer
  type: LoadBalancer
---
apiVersion: batch/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: CronJob
metadata:
  name: itunes-scraper-analyzer
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: itunes-scraper-analyzer
            image: itunes-scraper-analyzer:latest
            command: ["node", "server.js"]
            imagePullPolicy: Never
            env:
            - name: MONGO_HOST
              value: itunes-scraper-mongo
            - name: MONGO_USER
              value: podcasts
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-pass
                  key: pass
            - name: POSTGRES_DB_HOST
              value: itunes-scraper-psql
            - name: POSTGRES_DB_NAME
              value: podcasts
            - name: POSTGRES_USER
              value: podcasts
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-pass
                  key: password
            ports:
            - containerPort: 3000
              name: analyzer
          restartPolicy: OnFailure
