apiVersion: v1
kind: Service
metadata:
  name: itunes-scraper-analyzer
  labels:
    app: itunes-scraper
spec:
  ports:
    - port: 3000
  selector:
    app: itunes-scraper
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: itunes-scraper-analyzer
  labels:
    app: itunes-scraper
spec:
  selector:
    matchLabels:
      app: itunes-scraper
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: itunes-scraper
        tier: backend
    spec:
      containers:
      - image: jacopoteneggi/itunes-scraper:latest
        name: itunes-scraper-analyzer
        env:
        - name: POSTGRES_DB_HOST
          value: itunes-scraper-psql
        - name: POSTGRES_USER
          value: "podcasts"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql-pass
              key: password
        ports:
        - containerPort: 3000
          name: analyzer
